### ISSUE TITLE
Physical paths disclosure - add option to not display errors on web pages

### ISSUE THREAD

**Issue by Worst45** [viewvc/viewvc#140]
Hello,

when viewvc is called with a malformed URL, it displays physical paths of my server in the error stacktrace.
Example:
**https://myserver/viewvc/cd?pathrev=zzyxla**
> **An Exception Has Occurred**
> **Python Traceback**
> 
> Traceback (most recent call last):
>   File "/usr/lib/viewvc/lib/viewvc.py", line 4844, in main
>     request.run_viewvc()
>   File "/usr/lib/viewvc/lib/viewvc.py", line 305, in run_viewvc
>     self.pathtype = _repos_pathtype(self.repos, path_parts, pathrev)
>   File "/usr/lib/viewvc/lib/viewvc.py", line 753, in _repos_pathtype
>     return repos.itemtype(path_parts, rev)
>   File "/usr/lib/viewvc/lib/vclib/svn/svn_repos.py", line 410, in itemtype
>     rev = self._getrev(rev)
>   File "/usr/lib/viewvc/lib/vclib/svn/svn_repos.py", line 849, in _getrev
>     raise vclib.InvalidRevision(rev)
> InvalidRevision: Invalid revision zzyxla

Is it possible to add an option in the config file to not display stacktraces on the web page? Those information should still be sent to syslog, but not displayed

This was detected by [Nessus Vulnerability Scanner](https://www.tenable.com/products/nessus-vulnerability-scanner), that I use to check my servers security. Here is the check output:

> 
> **Description**
> At least one web application hosted on the remote web server discloses the physical path to its directories when a malformed request is sent to it.
> 
> Leaking this kind of information may help an attacker fine-tune attacks against the application and its backend.
> 
> **Solution**
> Filter error messages containing path information.
> 
> **Output**
> ```
>     The request GET /viewvc/cd?pathrev=zzyxla HTTP/1.1
>     Host: <myhostname>
>     Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1
>     Accept-Language: en
>     Connection: Keep-Alive
>     User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
>     Pragma: no-cache
>     Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*
> ```
>
>     produces the following path information :
> ```
>     <p><pre>
>     Traceback (most recent call last):
>     File &quot;/usr/lib/viewvc/lib/viewvc.py&quot;, line 4844, in main
>     request.run_viewvc()
>     File &quot;/usr/lib/viewvc/lib/viewvc.py&quot;, line 305, in run_viewvc
```

**Comment by Worst45** [comment]
With fast tests, I found that you can "just" add something like:
`sys.tracebacklimit=0`

at the beginig of lib/viewvc.py and others python files when the option is activated

Result output:

> **An Exception Has Occurred**
> **Python Traceback**
> 
> Traceback (most recent call last):
> InvalidRevision: Invalid revision zzyxla

**Comment by cmpilato** [comment]
ViewVC's error display is also templatized, and designed to be modified.  So another option here would be to edit your `error.ezt` file, and simply remove the logic that present the `[stacktrace]` data, which is this whole block:

    [if-any msg][else]
    <h4>Python Traceback</h4>
    <p><pre>
    [stacktrace]
    </pre></p>
    [end]

I do, however, like your `sys.tracebacklimit = 0` suggestion. I think I'd want to integrate it in a way that the error output isn't still presented as a traceback (because let's face it -- there's nothing "trace" or "back" about it at that point).  I'm curious also as to the effect this has on the stacktraces that wind up in Apache's error_log when something truly bad happens.  I suppose those, likewise, would be truncated, which would actually be a mixed blessing: fewer lines of spew in the log, but less context to use when diagnosing the problem.
