### ISSUE TITLE
What is recommended?: standalone vs fastcgi ?

### ISSUE THREAD

**Issue by cmanley** [viewvc/viewvc#189]
I've tried the standalone version of viewvc in a Docker container and it seems to work fine. Are there any recommendations when choosing between standalone viewvc vs viewvc in a fastcgi server?
The latter requires additional software (supervisord, nginx, and a fastcgi daemon).

**Comment by cmpilato** [comment]
I would think that a FastCGI daemon would probably be more hardened than standalone.py.  Maybe it's just me, but since joining this project I've always kinda seen standalone.py as a lightweight framework to allow quick testing of ViewVC.  I know that there are folks who've used it in production in the past successfully, so I don't mean to imply that there are known weaknesses in standalone.py.  It's just a "gut feeling", I guess.
