### ISSUE TITLE
`ERROR 1067 (42000) at line 14: Invalid default value for 'ci_when'`

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#200]
I had the same problem as dev1098: `ERROR 1067 (42000) at line 14: Invalid default value for 'ci_when'` I edited the make-database script and gave 'ci_when' a proper DEFAULT value. After that the database was created successfully.

_Originally posted by @mind12 in https://github.com/viewvc/viewvc/issues/141#issuecomment-323672879_

**Comment by futatuki** [comment]
(from my comment in #141, as a note)
This is caused by about default value of column '`ci_when`' in table '`checkin`',  if `ALLOW_INVALID_DATES` option is disabled on the MySQL server.
https://dev.mysql.com/doc/refman/8.0/en/datetime.html
I think current default value '`0000-00-00 00:00:00`' is reasonable if `ALLOW_INVALID_DATES` is enabled, but I have no idea what value is suitable for default if this option is diabled.

**Comment by cmpilato** [comment]
I do not believe the value is suitable if `ALLOW_INVALID_DATES` is disabled.  We can't use `NULL` because the column disallows that value.  I think the best we could do is use some other valid sentinel.  From those same docs:

> The DATETIME type is used for values that contain both date and time parts. MySQL retrieves and displays DATETIME values in 'YYYY-MM-DD hh:mm:ss' format. The supported range is '1000-01-01 00:00:00' to '9999-12-31 23:59:59'.

So maybe we just use `1000-01-01 00:00:00` and call it a day?

**Comment by futatuki** [comment]
If we want to support setting `ALLOW_INVALID_DATES` is disabled, there may be some other parts to check values to pass as ci_when, e.g. lib/cvsdb.py seems to use 0.0.
https://github.com/viewvc/viewvc/blob/master/lib/cvsdb.py#L300

**Comment by cmpilato** [comment]
@futatuki If I'm reading that code correctly, 0.0 is used as the default number of "ticks" (since the Epoch), but not as an actual ci_when value.  `dbi.DateTimeFromTicks(0.0)` should yield the Epoch itself, which is definitely a valid MySQL date.

**Comment by futatuki** [comment]
Aha, you are right. And perhaps I saw its value when I was testing my Python 3 support code for cvsdb, because of my incorrect code :-)
Use of `ci_when`  are only in  `bin/make-database` and `lib/cvsdb.y`, and in `lib/cvsdb.py` other place of usage are all reading (`SELECT`), so I think there is no more place to change.
