### ISSUE TITLE
Unable to navigate to non-ascii file names

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#218]
When running ViewVC 1.3.0-dev under WSGI, I'm unable to navigate to a file with a non-ascii name from the directory listing that presents it.  Attempting to click on a file name such as `测试文件.txt` results in an exception about being unable to view `æµè¯æä»¶.txt`.  In ViewVC 1.2, this works as expected.

I'm not sure yet if this is limited to the WSGI deployment model alone, or it it also manifests under CGI.  And I can't currently compare against ViewVC 1.2.x or 1.1.x, because my mod_wsgi has already been upgraded to a version requiring Python 3.x.

**Comment by futatuki** [comment]
In standalone server in Python 3.6, if I don't provide UTF-8 in start up,  revision log view for UTF-8 file name (e.g. URL: http:// 127.0.0.1:49152/viewvc/test_repo/trunk/%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D.txt?view=log) causes server crush, with Exception:

```
Exception happened during processing of request from ('127.0.0.1', 64606)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "bin/standalone.py", line 122, in do_GET
    self.handle_request('GET')
  File "bin/standalone.py", line 131, in handle_request
    self.run_viewvc()
  File "bin/standalone.py", line 257, in run_viewvc
    self.run_viewvc()
  File "bin/standalone.py", line 257, in run_viewvc
    env['PATH_INFO'] = uqrest
  File "/usr/local/lib/python3.6/os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/lib/python3.6/os.py", line 745, in encode
    return value.encode(encoding, 'surrogateescape')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-24: ord
inal not in range(128)
```

where 'ascii' is a result of sys.getfilesystemencoding() in this context.
As far as I read os.py in Python 3.6 and 3.7, os.environ.__setitem__, os.environ.__get_item__ uses sysgetfilesystemencoding to encode or decode item values.

Is it related? or another issue?

**Comment by cmpilato** [comment]
Possibly related.  My understanding is that mod_wsgi is kinda bound by the various specs to treating the CGI gateway environment variables as ascii-compatible strings.  Some links of interest I intend to eventually parse:

- https://www.python.org/dev/peps/pep-0333/#unicode-issues for something possibly related
- https://code.google.com/archive/p/modwsgi/wikis/SupportForPython3X.wiki
- https://bugs.python.org/issue16679

**Comment by cmpilato** [comment]
I've made changes that fix this on my system.  I _think_ it's an appropriate general fix, but would appreciate @futatuki giving this a post-commit review.  Reopen this issue as necessary.

**Comment by futatuki** [comment]
Function recode_latin1_path can be cause uncought UnicodeDecodeError out side of viewvc.main()  if user provide a broken path (broken as UTF-8) by specify manually, or  by accident (,  or non UTF-8 path in CVS repo,  if we support it).  So I think it is better to use 'surrogateescape' to decode, and handle it within viewvc.main in path validation.

e.g. `http://127.0.0.1:49152/viewvc/test_repo/trunk/%c6%fc%cb%dc%b8%ec%5%d5%a5%a1%a5%a4%a5%eb.txt` is a mistaken 'euc-jp' encoded URL of `http://127.0.0.1:49152/viewvc/test_repo/trunk/日本語ファイル名.txt`. I think this will cause "Internal Server error" in wsgi.  (Standalone server has another problem about it, and I've not see cgi server, however they may be other issues.)

**Comment by cmpilato** [comment]
Hrm.  My hesitation to move this into `viewvc.py` is that I've got three servers running simultaneously (Apache+WSGI, Apache+CGI, and standalone.py) and *only* WSGI seems to exhibit the problem.

You mention the non-UTF8 path in CVS ... that's a real concern.  With ViewVC 1.2+Python2, I seem to recall that paths are all just effectively bytestrings.  So if they're UTF-8 (as with Subversion or CVS hosted on a UTF-8 system), their URLs encode like you'd expect UTF-8-as-bytes to %-encode.  If they're something else in CVS (Shift-JIS, Big5, etc.) it's the same story, whatever-as-bytes, %-encoded.

But if we're passing around Unicode strings for paths in Python3, what does that mean for CVS where the filesystem encoding is not UTF-8?  Is that where the per-repos `default_encoding` comes into play?

**Comment by futatuki** [comment]
> Hrm. My hesitation to move this into `viewvc.py` is that I've got three servers running simultaneously (Apache+WSGI, Apache+CGI, and standalone.py) and _only_ WSGI seems to exhibit the problem.
> 

Ah, I've a bit missunderstood.  As `Request.run_viewvc()` access to these parameters through `sapi.Server.params()` interface, so transcode can be moved in it. Then we can trap the exception.

In standalone server, query string is parsed in `ViewVCHTTPRequestHandler.run_viewvc()` and PATH_INFO is set to environment variable, as a result of `urllib.parse.unquote()` (as %-encoded UTF-8 string, with `'replace'` handler).  Then it is parsed again by `cgi.parse()` in `StandaloneServer.params()` (= `CgiServer.params()`), but PATH_INFO is unchanged because it is already %-decoded.

In CGI server, it seems the behaviour of our code depends on locale environment variables and Python version.  It is because `cgi.parse()` uses `encoding` attribute in input str stream passed as `fp`  (in our code `fp = None`, which means it uses `sys.stdin`) to decode,  and how Python interpreter decide sys.stdin.encoding is different in Python version.

(I'll comment about non-UTF8 path in CVS later)

**Comment by futatuki** [comment]
I forgot mention that cgi.parse also use `'replace'` errors handler when decode %-decoded bytes string to Unicode. It calls `urllib.parse_parse_qs()` without specifying `errors` optional parameter.

**Comment by cmpilato** [comment]
I don't mind using an `errors=` fallback option to avoid UnicodeDecodeErrors.  That's fine.  But as in other areas of ViewVC, I think it's important that the central functionality (`lib/viewvc.py`) not be tasked with working out the complications that are specific to any one particular type of deployment model.  So if we say that ViewVC expects `os.environ['PATH_INFO']` to return a string instead of bytes (for example), then it's the server-specific peripherals that need to ensure that.  You're right, though -- we could make those guarantees in the `sapi` module, and I think it's wise to do so.

**Comment by futatuki** [comment]
I think there are two way to handle non-UTF8 paths as str for internal representation, for CVS repos -- decode paths as repos encoding (like Subversion repos), and always decode paths as UTF8. In both of the cases,  error handler should be `'surrogateescape'` so that hold original path information in bytes representation, because traditional Unix filesystems don't have character encodings themselves, they allows different encodings of file names in a same directry, or even no suitable encoding.

In the former way, we can directly use internal paths representation for display in most case, however, if repos encoding setting is changed, a URLs for each files are also changed.

In the latter way, we the path and URL is invariable, independent to repos encoding. However we can't directly use internal path object for display as users want to see (i.e., file path, file names as repos encoding).

Anyway, I think it is need to work to ensure encodings we want.

**Comment by futatuki** [comment]
> In the former way, we can directly use internal paths representation for display in most case, however, if repos encoding setting is changed, a URLs for each files are also changed.

I overlooked that even this case,  once we should decode PATH_INFO as UTF8 (or default encoding setting in config file, not per-repos encoding), because it is done before determine the path is for which repos.

**Comment by futatuki** [comment]
@cmpilato I beleve it was solved both on CVS and Subversion's repos. If there still exist some problems about it, let's reopen this issuue, or make a new issue.
