### ISSUE TITLE
ViewVC screen blank

### ISSUE THREAD

**Issue by bendcunha** [viewvc/viewvc#269]
Dear All,
I have setup rancid with viewvc the first time with Just the first switch but when i i try to access the site using my browser that is http://ip-address/viewvc I just get a blank page . Under Name no directories are shown I have attached the screenshot.
Also I have seen that under var/switches/config directory my switch config is backed up
using Centos 8 64 bit
rancid-3.12-1.el8.x86_64
viewvc-1.3.0-dev-20210817

attached the screenshot

Appreciate your kind help and advice

Thanks and regards

simon
![viewvc-screen](https://user-images.githubusercontent.com/88819819/130191945-10e60148-9ab8-4d76-9bbd-f7de20b36c52.JPG)

**Comment by futatuki** [comment]
I don't know about rancid, however I don't think that rancid can care about ViewVC automatically. So I think you need to setup ViewVC for rancid manually, and you couldn't complete it yet.

- Make sure that rancid stores config file(s) to CVS or Subversion repository. Try to checkout config file(s) by using command line client `cvs` or `svn` as UID which uses rancid.
- Make sure that you specify your rancid repository path in cvs_roots (for CVS repos) or svn_roots (for Subversion repos), in viewvc.conf.
- Make sure that the repository can readable by ViewVC.  Check the repository permission for UID which used by ViewVC, and check SELinux fcontext and policy for httpd and its children.
- Check the httpd error log and audit log.

**Comment by bendcunha** [comment]
Thanks a lot dear .. Actually i have followed the below docs for rancid and viewVC

https://nsrc.org/activities/agendas/en/nmm-5-days/netmgmt/en/rancid/exercises-rancid.html

https://geekdudes.wordpress.com/2020/01/16/installing-and-configuring-rancid-on-centos-8/

thanks once again and will check it out as per your advice


regards

simon

**Comment by bendcunha** [comment]
Dear All,
Thanks a lot for the replyBy the way I did find out the repo where rancid stores the file but setting the path I still face issues---------------I run the below command.
svn look tree /var/rancid/CVS and it display only /
but svn look tree /var/rancid/svn it display me the below
/ Routers/  .cvsignore  configs/   .cvsignore  router.db Switches/  .cvsignore  configs/   .cvsignore   192.168.1.100  router.db-------------------------------------------
hence in viewvc.conf I have the statement----  svn_roots = rancid: /var/rancid/svnbut when I try to access http://ip/viewvc it says:----------An Exception Has Occurred

Python Traceback


ModuleNotFoundError: No module named 'svn'------------------but if i have the below in viewvc.conf root_parents = /var/rancid/CVS : cvs 
no error but browser only displays page with no repositaryI tried to add paths but no luckappreciate your advice and helpIf you need any more information please do askthanks and regards
simon




    On Friday, August 20, 2021, 11:21:43 AM GMT+3, FUTATSUKI Yasuhito ***@***.***> wrote:  
 
 


I don't know about rancid, however I don't think that rancid can care about ViewVC automatically. So I think you need to setup ViewVC for rancid manually, and you couldn't complete it yet.
   
   - Make sure that rancid stores config file(s) to CVS or Subversion repository. Try to checkout config file(s) by using command line client cvs or svn as UID which uses rancid.
   - Make sure that you specify your rancid repository path in cvs_roots (for CVS repos) or svn_roots (for Subversion repos), in viewvc.conf.
   - Make sure that the repository can readable by ViewVC. Check the repository permission for UID which used by ViewVC, and check SELinux fcontext and policy for httpd and its children.
   - Check the httpd error log and audit log.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bendcunha** [comment]
Dear All,
Thanks a lot for the reply
By the way I did find out the repo where rancid stores the file but setting the path I still face issues
---------------
I run the below command.
svn look tree /var/rancid/CVS 
and it display only 
/
but svn look tree
 /var/rancid/svn
displays me the below
/
Routers/ 
 .cvsignore  
configs/  
 .cvsignore 
 router.db 
Switches/ 
 .cvsignore 
 configs/   
.cvsignore   
192.168.1.100
  router.db
-------------------------------------------
hence in viewvc.conf I have the statement
---- 
 svn_roots = rancid: /var/rancid/svn
but when I try to access http://ip/viewvc it says
:----------
An Exception Has Occurred
Python Traceback
ModuleNotFoundError:
 No module named 'svn'
------------------
but if i have the below in
viewvc.conf root_parents = /var/rancid/CVS : cvs

no error but browser only displays page with no repository 
I tried to add paths but no luck
appreciate your advice and help
If you need any more information please do ask
thanks and regards
simon

**Comment by futatuki** [comment]
Make sure which you are using CVS or Subversion (or Git?), as a backend version control system of rancid. (I guess you are using Subversion, because of result of your '`svn look tree`' (I think it was '`svnlook tree`', though).

Then please read [`INSTALL`](https://github.com/viewvc/viewvc/blob/master/INSTALL) document of ViewVC, especially section ['**Configuring ViewVC**'](https://github.com/viewvc/viewvc/blob/master/INSTALL#configuring-viewvc), and [**Serving CVS Repositories**](https://github.com/viewvc/viewvc/blob/master/INSTALL#serving-cvs-repositories) for CVS or [**Serving Subversion Repositories**](https://github.com/viewvc/viewvc/blob/master/INSTALL#serving-subversion-repositories) for Subversion, to understand what you are you doing. Please see also comments in [`viewvc.conf.dist`](https://github.com/viewvc/viewvc/blob/master/conf/viewvc.conf.dist) file for understanding per configuration parameters.

> An Exception Has Occurred
> Python Traceback
> ModuleNotFoundError:
> No module named 'svn'

If you want to use ViewVC with Subversion repository, you need to install Python bindings module of Subversion, as the [`INSTALL`](https://github.com/viewvc/viewvc/blob/master/INSTALL) document says. How to install it depends on how do you install Subversion,
but generally if you installed Subversion from package provided by distribution or 3rd party, Python bindings module package also might be provided by them.

**Comment by futatuki** [comment]
> > An Exception Has Occurred
> > Python Traceback
> > ModuleNotFoundError:
> > No module named 'svn'
> 
Those output tells that ViewVC tried to import Python bindings module of Subversion named '`svn`', but it couldn't import because the Python interpreter couldn't find it because it was not installed or installed but it was placed out of module search paths.

So I wrote below assuming the former case.

> If you want to use ViewVC with Subversion repository, you need to install Python bindings module of Subversion, as the [`INSTALL`](https://github.com/viewvc/viewvc/blob/master/INSTALL) document says. How to install it depends on how do you install Subversion,
> but generally if you installed Subversion from package provided by distribution or 3rd party, Python bindings module package also might be provided by them.

**Comment by bendcunha** [comment]
Dear Futatuki and guys,

Sorry for the delayed response
I got viewvc working

Actually I did the installation of Centos 8 and rancid and viewvc from scratch following the below link
and all went well
https://systemstechblog.wordpress.com/2015/01/03/install-rancid-and-viewvc-on-centos-7/
and its working with CVS also

What I presume is earlier install of rancid i did with dnf  so guess there was confusions in the paths

once againn thanks for all the support

regards

simon
