### ISSUE TITLE
run viewvc-install fail on Debian 11 VM

### ISSUE THREAD

**Issue by 3956ray** [viewvc/viewvc#294]
Hi All,

I got a problem when I run 1.2.1 viewvc-install. I receive a log that 

Traceback (most recent call last):
  File "/home/myusername/svnViewvc/viewvc-1.2.1/./viewvc-install", line 38, in <module>
    import viewvc
  File "./lib/viewvc.py", line 3212
    except OSError,v:
                  ^
SyntaxError: invalid syntax

os: Debian 11
python --version: Python 3.9.2
viewvc: 1.2.1

**Comment by ChristopherSchultz** [comment]
I had a similar problem (Upgraded from Debian 10 -> 11 and viewvc – which had been a Debian-provided package in Debian 10 – was deleted and is no longer supported. It appears that's due to the [release manager not being interested anymore](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935691) and also because of the Python2 requirement. (Debian 11 attempts to remove Python 2, but unlike viewvc, the upgrade process retains those packages but recommends their removal after upgrade.)

Anyhow, I was able to get viewvc working again following these two steps on Debian 11 (Bullseye):

1. Install viewvc from "source" (untar the tarball, run ./viewvc-install)
2. Install the required Debian package called `python3-subversion`
3. Copy the viewvc.cgi script into my pre-existing `cgi-bin` directory
4. Re-configure `viewvc.conf` in a similar way to my previous install

Now viewvc works for me on Debian 11.

**Comment by futatuki** [comment]
As the problem seems to be resolved,  close this issue.
