### ISSUE TITLE
ImportError: /usr/lib/python2.7/dist-packages/libsvn/_core.x86_64-linux-gnu.so: undefined symbol: svn_relpath__internal_style

### ISSUE THREAD

**Issue by robertfetter** [viewvc/viewvc#304]
**Describe the bug**
It seems that ViewVC uses a ,so for things. So to get this to work I wrote another cgi to launch things named myviewvc,cgi:
#!/bin/sh
export PYTHONPATH=/usr/lib/python2.7/dist-packages/libsvn
/usr/lib/cgi-bin/viewvc.cgi
Upon running it I get:
ImportError: /usr/lib/python2.7/dist-packages/libsvn/_core.x86_64-linux-gnu.so: undefined symbol: svn_relpath__internal_style
Not good. Any thoughts?
**Steps to reproduce the behavior**

**Expected behavior**
Things should work.
**Additional context**
Add any other context about the problem here.  Consider attaching any helpful screenshots.

**Comment by cmpilato** [comment]
This seems like a problem with Subversion's python bindings (which ViewVC depends on to do its thing for Subversion repositories), and specifically an issue with the packaging of those bindings on your specific platform.  Please raise the issue with that community at https://subversion.apache.org/reporting-issues.html.

**Comment by futatuki** [comment]
It seems that `/usr/lib/python2.7/dist-packages/libsvn/_core.x86_64-linux-gnu.so` in your environment requests older version of  libsvn_subr than which of installed. 

`svn_relpath__internal_style` is renamed to `svn_relpath__make_internal` in r1850611, between Subversion 1.11.0 and 1.12.0. 

I guess that you copied (or force install) old package of Subversion Python bindings regardlessly version consistency between shared libraries.

**Comment by futatuki** [comment]
I also guess that @robetfetter did unusual operation on installing required softwares for getting ViewVC to work because the packages provided by the distributor is not support it.  If it is so,  the issue itself is not a problem of Subversion's python bindings, althogh it may be a part of this issue, but getting ViewVC to work.  So I'd like to continue this conversation here.

@robertfetter ,  could you tell us what version of ViewVC do you want to get to work, and what did you do for it in detail, e.g.  installed packages (or softwares built and installed from source) with version,  if you copied files from other environment,  their origins, etc.

**Comment by robertfetter** [comment]
Thank you for your quick response.  I sent an issue to subverson.

**Comment by futatuki** [comment]
See also the [thread about this on users@subversion.apache.org](https://lists.apache.org/thread/vcf1p4zz1hh9ndxgcyox322btf0j7dk2).
