### ISSUE TITLE
Using ViewVC v1.3 against a subversion repository, enabling tar files does not create properly formatted output for symlinks

### ISSUE THREAD

**Issue by ddfourni1** [viewvc/viewvc#344]
**Describe the bug**
I have a repository with files properly identified as symlinks (they contain the svn:special : * property) linking to files within the same directory. When I enable the 'tar' view and use the 'Download Tarball' link for the directory containing the files, the resulting tarball does not identify the symlink files as symlinks and the contents are "link {FILENAME}" where {FILENAME} is the file the symlinks are intended to point to. 

1. Enable the 'tar' view in the ViewVC configuration file.
2. Create and Commit a directory containing files with symlinks to the files. Ensure to properly add the svn:special : * property to the symlinks. 
3. In ViewVC Navigate to the directory (or the parent directory) containing the files.
4. Click the "Download Tarball" link in the ViewVC UI
5. Open the tar file, the contents for the symlinks will not be symlinks, but regular files with the contents 'link {FILENAME}"

**Expected behavior**
The resulting tarball should contain the symlinks identified as symlinks.

**Additional context**
The code on line 4069 of lib/viewvc.py:
>if hasattr(request.repos, 'get_symlink_target'): 

Never returns true. If this is modified to always attempt to set symlink_target, an exception is thrown when trying to read the contents for each symlink target that is encountered.

**Comment by ddfourni1** [comment]
[344_fix_svn_tarball_symlinks.PATCH](https://github.com/viewvc/viewvc/files/14962917/344_fix_svn_tarball_symlinks.PATCH)
This patch seems to resolve it for me, not sure how to run your tests to validate.

**Comment by futatuki** [comment]
Thank you for the report.

> The code on line 4069 of lib/viewvc.py:
> 
> >    if hasattr(request.repos, 'get_symlink_target'):
> 
> Never returns true. 

This analysis seems incorrect.  If `request.repos` is a instance of `vclib.svn.svn_repos.LocalSubversionRepository`  or `vclib.svn.svn_ra.RemoteSubversionRepository`,  it has `request.repos.get_symlink_target()`.

However, those methods `get_symlink_target()` has a bytes-str confusion bug, as your patch shows (although the patch cannot be applied HEAD of master branch. Which version (commit hash, or date of the snapshot) of ViewVC 1.3-dev do you see?).

In the current code,  local variable `pathspec` in `get_symlink_target()` is a `bytes` because it is read as a binary, so it is correct that you compare it with `b'link '`.  However vclib should return paths as str by design. So we should decode it as a `str`.

**Comment by futatuki** [comment]
> ...not sure how to run your tests to validate.

The test on PR is syntax and style checking by using [`flak8`](https://flake8.pycqa.org/).  To check it locally, install `flake8` and then run `flake8 --config=.flake8` on the top of source tree.

**Comment by futatuki** [comment]
I've made a PR #345 address this issue.  Although there seems to be an issue on encoding of filename difference between CVS, Subversion and tar utility,  it works even if a symlink target has an Unicode path in UTF-8 encoding (checked with bsdtar (libarchive) and GNU tar).

**Comment by futatuki** [comment]
The PR #345 addressed this issue was merged into master (1.3-dev branch).
The fixed version of snapshot will be available from https://viewvc.org/nightly/ within a day,  viewvc-1.3-dev-20240415 or later.

If you are using a package provided by a OS distribution, please ask the maintainer of the package to update it to the latest snapshot.  (I guess from your patch, you are using a snapshot before 2021-07-16, before style fix had been merged).

**Comment by ddfourni1** [comment]
Thanks - That resolves the issue!
