### ISSUE TITLE
Is the sample config file correct about "web-friendly image files"?

### ISSUE THREAD

**Issue by rwv37** [viewvc/viewvc#360]
The sample config file says:
```
## NOTE: ViewVC's 'markup' view can show web-friendly image files
## ("image/jpeg", "image/gif", "image/png") as images embedded in the
## 'markup' view page, and prefers to do so.
```
I've been trying to make this happen for a while now (for example making sure mime types are set properly on the files and described in a configured mime_types_files file), but haven't been able to. It always just tells me "This file's contents are not viewable."

If it's true, how do you do it?

**Comment by futatuki** [comment]
To use the feature that shows web-friendly image files:

- the mime-type of the file, showed as 'Conent Type:' should be one of 'image/gif', 'image/jpeg', 'image/png'
- the mime-type of the file should listed in `binary_mime_types` config option(, as described in the comment in sample config file)
-  `allowed_views`  config option contains `co` view.

The last one is not in by default, so I think it is the reason.

**Comment by rwv37** [comment]
Thanks, @futatuki. I was afraid of that (the "co" thing), as the sample config says that that's a security risk.

**Comment by futatuki** [comment]
That security risk is allowing users to get raw files, I think.  However if markup view is allowed by the config,  text files are shown in markup view, so the protection is only for binary files.

It seems that this behaviour was improved in the commits related to issue #216 (commit https://github.com/viewvc/viewvc/commit/40c7508c48e93a9b89282ddb5eb8c81682f1a389,  https://github.com/viewvc/viewvc/commit/40c7508c48e93a9b89282ddb5eb8c81682f1a389, and https://github.com/viewvc/viewvc/commit/f7fd7a354a95299a9df20467dadd8601eb7c4da5).

I think the 3rd conditional above is extra and that behaviour can be controled in 2nd conditional.

@cmpilato how do you think about it?

**Comment by cmpilato** [comment]
Yeah, the warning around the "co" view is largely aimed at folks whose ViewVC instances display source code repositories where the commit access isn't well-gated.  Because "co" allows files to be served up essentially the same way a regular web browser would serve them, a malicious (or foolish) committer could commit HTML/JS files that "do bad things" -- scripts that get executed by the browser, etc.  But if those concerns don't apply to your situation, I wouldn't be concerned about enabling that view.

**Comment by rwv37** [comment]
@cmpilato I'm the only one who commits to the repository, but (generally speaking) I don't think it would be terribly wise of me to decide to enable a known security risk based upon the idea that I'm wise enough to make it not a concern, so thanks, but I won't be taking that route.

Couldn't there just be an option to display serve certain mime types (e.g. images) and not others (e.g. HTML), making sure to tell the browser what the mime type is, independent of the "co" option?

**Comment by cmpilato** [comment]
@rwv37 I respect your logic here, even though I suspect you've misunderstood the risk factors.

Admittedly, I'm concerning because the code in and around these features (the markup and checkout views, what is and isn't considered binary, character transcoding, mime types ... so very much ...) has been tweaked many times over the years, less as the result of a unified vision of correctness and more incrementally in response to requests by users (such as yours).  Hear me correctly, though:  **there's not a thing in the world wrong with these requests!**  I'm merely pointing out that this area of the codebase has suffered from a bit of "the whack-a-mole effect".  The good news (I guess?) is that I think that the current state of the code also fails to represent The Right Way, but was rather the necessary side-effect of several other factors.

I think what we're looking for is something that meets all the following criteria:

- Users who have the `co` view disabled in their `viewvc.conf` must have that honored going forward.  Said another way, we cannot "fix" this situation in any way that doesn't require an _explicit_ modification to the configuration files.
- Users must be allowed to configure ViewVC to serve up the raw "baby" data of viewable images _without_ exposing the raw "bathwater" data of other content types.
- Ideally, whatever new configuration we introduce doesn't add too much complexity to the matrix of configuration possibilities _already_ present in ViewVC.

Thinking through possible solutions, we could (for example) introduce an entirely new view (disallowed by default, like `co`) called `image`, which ViewVC uses only when formulating the URL that gets embedded into the `<img src="...` tag when serving up the markup view of "viewable images".  Admins who want this behavior would add `image` to the `allowed_views`.  That view's logic would decline to serve up anything when the view is disallowed or when the request is aimed at anything other than a web-friendly image.

And I'm sure there are other solutions, too.

@futatuki Have you any opinions about this?  What am I oversimplifying/forgetting?

**Comment by futatuki** [comment]
Sorry for delay.  It had taken for a while for me to understand the background, why new view is needed.  However I think I could understand it.

Your idea looks good to me.  The only thing I worry is about web clawlers, if they clawls images repeatedly, it takes much resources on server.  However the worry is not specific to this method.

**Comment by cmpilato** [comment]
> The only thing I worry is about web clawlers, if they clawls images repeatedly, it takes much resources on server. However the worry is not specific to this method.

Could this be helped by doing something obnoxious, such as having the `markup` view generate as part of the embedded image URL some timestamp-based parameter that the `image` view itself uses for validation?

For example, say I visit the `markup` view of a JPEG in my repository at `/repos/trunk/logo.jpg`.  ViewVC could stick `&expiration_dt=TS` (where TS is the current timestamp plus 10 minutes or something) on the URL that it generates and which the template uses in the `<img src="...">` tag.  The browser, of course, parses the DOM and see the `<img>` tag and heads off to fetch my JPEG.  But the `image` view could decline to handle requests that carry an "old" `expiration_dt`.

It's a (very) poor man's bot-buster, admittedly.  But maybe it protects just a little bit against crawlers?

**Comment by cmpilato** [comment]
> Your idea looks good to me.

I tried to dust the cobwebs off my brain and have a go at implementing the idea with PR #364.

**Comment by cmpilato** [comment]
#364 has been merged now.

@rwv37 Not sure if you're running from a Git checkout or nightly builds, but hopefully soon you can try out the new view.  _Should be_ as easy as adding `image` to the list of `allowed_views` (I mean, once the newer code is in place, of course).  I'm going to close this, but feel free to reopen if something still isn't working.

**Comment by rwv37** [comment]
Thanks very much!
